//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cierre_caja
    {
        public int ini_caja { get; set; }
        public int id_cierre { get; set; }
        public Nullable<double> credito { get; set; }
        public Nullable<double> tarjeta { get; set; }
        public double efectivo { get; set; }
        public int usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual login login { get; set; }
    }
}
