//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente_empresa
    {
        public Cliente_empresa()
        {
            this.mensajes = new HashSet<mensaje>();
        }
    
        public int idcliente { get; set; }
        public string nombre { get; set; }
        public string empresa { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string sistema { get; set; }
        public System.DateTime ingreso { get; set; }
        public string rnc { get; set; }
        public string estado { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<mensaje> mensajes { get; set; }
    }
}
