//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.CXC = new HashSet<CXC>();
            this.venta = new HashSet<venta>();
        }
    
        public int ID_Cliente { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Dirreccion { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Lugar_De_trabajo { get; set; }
        public string Cedula { get; set; }
        public double Limite_Credito { get; set; }
        public Nullable<bool> estatus { get; set; }
    
        public virtual ICollection<CXC> CXC { get; set; }
        public virtual ICollection<venta> venta { get; set; }
    }
}
