//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprobantes
    {
        public comprobantes()
        {
            this.registro_comprobantes = new HashSet<registro_comprobantes>();
        }
    
        public int idomprobantes { get; set; }
        public string Tipo { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string secuencia { get; set; }
        public string secuencia_finalizar { get; set; }
    
        public virtual ICollection<registro_comprobantes> registro_comprobantes { get; set; }
    }
}
