//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion
    {
        public configuracion()
        {
            this.login = new HashSet<login>();
        }
    
        public int idcconfig { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string rnc { get; set; }
        public string telefono { get; set; }
        public string ubicacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string empre { get; set; }
        public byte[] logo { get; set; }
        public string redes { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<double> p { get; set; }
        public string correo_empresarial { get; set; }
    
        public virtual ICollection<login> login { get; set; }
    }
}
