//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXC
    {
        public int ID_CXC { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ID_Cliente { get; set; }
        public double Monto { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<int> venta { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual venta venta1 { get; set; }
    }
}
