//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleVenta
    {
        public int indtll { get; set; }
        public Nullable<int> ventaid { get; set; }
        public Nullable<int> idproducto { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<double> itbis { get; set; }
    
        public virtual venta venta { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
