//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class gasto
    {
        public int idgasto { get; set; }
        public string detalle { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> iduser { get; set; }
    
        public virtual login login { get; set; }
    }
}
