//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int ID_Inventario { get; set; }
        public int Producto_Id { get; set; }
        public double entrada { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public Nullable<int> tipo_operacion { get; set; }
        public Nullable<double> salida { get; set; }
    
        public virtual tipo_operacion tipo_operacion1 { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
