//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public login()
        {
            this.Cierre_caja = new HashSet<Cierre_caja>();
            this.gasto = new HashSet<gasto>();
            this.pagos = new HashSet<pagos>();
            this.venta = new HashSet<venta>();
        }
    
        public int iduser { get; set; }
        public string nombre { get; set; }
        public string usuario { get; set; }
        public string pass { get; set; }
        public int tipo { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> empresa { get; set; }
    
        public virtual ICollection<Cierre_caja> Cierre_caja { get; set; }
        public virtual configuracion configuracion { get; set; }
        public virtual ICollection<gasto> gasto { get; set; }
        public virtual tipoUsuario tipoUsuario { get; set; }
        public virtual ICollection<pagos> pagos { get; set; }
        public virtual ICollection<venta> venta { get; set; }
    }
}
