//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class beutyEntities : DbContext
    {
        public beutyEntities()
            : base("name=beutyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categoria> categoria { get; set; }
        public DbSet<Cierre_caja> Cierre_caja { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<comprobantes> comprobantes { get; set; }
        public DbSet<configuracion> configuracion { get; set; }
        public DbSet<cotizacion> cotizacion { get; set; }
        public DbSet<CXC> CXC { get; set; }
        public DbSet<dbCotizacion> dbCotizacion { get; set; }
        public DbSet<detalleVenta> detalleVenta { get; set; }
        public DbSet<empleado> empleado { get; set; }
        public DbSet<gasto> gasto { get; set; }
        public DbSet<Inventario> Inventario { get; set; }
        public DbSet<login> login { get; set; }
        public DbSet<Metodo_de_Pago> Metodo_de_Pago { get; set; }
        public DbSet<pagos> pagos { get; set; }
        public DbSet<registro_comprobantes> registro_comprobantes { get; set; }
        public DbSet<reparacion> reparacion { get; set; }
        public DbSet<suplidor> suplidor { get; set; }
        public DbSet<taller> taller { get; set; }
        public DbSet<tipo_operacion> tipo_operacion { get; set; }
        public DbSet<tipoUsuario> tipoUsuario { get; set; }
        public DbSet<venta> venta { get; set; }
        public DbSet<REPORTE_CXC> REPORTE_CXC { get; set; }
        public DbSet<View_cotizacion> View_cotizacion { get; set; }
        public DbSet<View_Credito> View_Credito { get; set; }
        public DbSet<View_cxc> View_cxc { get; set; }
        public DbSet<View_descuento> View_descuento { get; set; }
        public DbSet<View_factura> View_factura { get; set; }
        public DbSet<View_ganancias> View_ganancias { get; set; }
        public DbSet<View_inventario> View_inventario { get; set; }
        public DbSet<View_productos> View_productos { get; set; }
        public DbSet<View_reporte_inventario> View_reporte_inventario { get; set; }
        public DbSet<View_stock> View_stock { get; set; }
        public DbSet<Producto> Producto { get; set; }
    }
}
