//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sdeptech_softmarketEntities1 : DbContext
    {
        public sdeptech_softmarketEntities1()
            : base("name=sdeptech_softmarketEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente_empresa> Cliente_empresa { get; set; }
        public DbSet<mensaje> mensajes { get; set; }
        public DbSet<acepta_terminos> acepta_terminos { get; set; }
        public DbSet<licencia> licencias { get; set; }
        public DbSet<serial> serials { get; set; }
    }
}
