//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.detalleVenta = new HashSet<detalleVenta>();
            this.Inventario = new HashSet<Inventario>();
        }
    
        public int Codigo_ID { get; set; }
        public string codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<int> Suplidor { get; set; }
        public string Descripcion_Producto { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<double> precio_neto { get; set; }
        public Nullable<double> precio_salida { get; set; }
        public Nullable<double> impuesto { get; set; }
        public Nullable<System.DateTime> fecha_entrada { get; set; }
        public Nullable<bool> itbis { get; set; }
    
        public virtual categoria categoria1 { get; set; }
        public virtual ICollection<detalleVenta> detalleVenta { get; set; }
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual suplidor suplidor1 { get; set; }
    }
}
