//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class taller
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string detalle { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<double> total { get; set; }
        public string referencia { get; set; }
        public string mecanico { get; set; }
        public Nullable<int> idmecanico { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
