//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_cotizacion
    {
        public int idcotiza { get; set; }
        public string cliente { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<bool> estado { get; set; }
        public string rnc { get; set; }
        public Nullable<double> totalItbis { get; set; }
        public int idcotizacion { get; set; }
        public string nombre { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<double> totalProducto { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string codigo { get; set; }
        public Nullable<System.DateTime> Expr4 { get; set; }
        public Nullable<double> totalCotizacion { get; set; }
        public Nullable<int> Expr5 { get; set; }
        public Nullable<int> idprd { get; set; }
        public Nullable<double> itbis { get; set; }
        public string tipodocumento { get; set; }
    }
}
