//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ganancias
    {
        public string codigo { get; set; }
        public string Nombre { get; set; }
        public int Codigo_ID { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> precio_salida { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> precio_neto { get; set; }
        public int indtll { get; set; }
        public Nullable<double> Ganancia { get; set; }
        public int idventa { get; set; }
        public Nullable<double> total_1 { get; set; }
        public Nullable<double> total_g { get; set; }
        public string cliente { get; set; }
    }
}
