//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_inventario
    {
        public int Codigo_ID { get; set; }
        public string codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Categoria { get; set; }
        public int idsuplidor { get; set; }
        public string Expr1 { get; set; }
        public string Descripcion_Producto { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<double> precio_neto { get; set; }
        public Nullable<double> precio_salida { get; set; }
        public int idcategoria { get; set; }
        public string Expr2 { get; set; }
        public Nullable<bool> itbis { get; set; }
    }
}
