//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_cxc
    {
        public int ID_Cliente { get; set; }
        public string Nombre { get; set; }
        public int ID_CXC { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Monto { get; set; }
        public string Cedula { get; set; }
        public string Apellidos { get; set; }
    }
}
