//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_productos
    {
        public int Codigo_ID { get; set; }
        public int Producto_Id { get; set; }
        public string codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> entredas { get; set; }
        public Nullable<double> salidas { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> precio_salida { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> Categoria { get; set; }
    }
}
