//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_factura
    {
        public int Codigo_ID { get; set; }
        public string Descripcion_Producto { get; set; }
        public int ID_Cliente { get; set; }
        public string Nombre { get; set; }
        public int ID_Metodo { get; set; }
        public string metodo { get; set; }
        public int iduser { get; set; }
        public string usuario { get; set; }
        public int idventa { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<double> efectivo { get; set; }
        public Nullable<double> tarjeta { get; set; }
        public Nullable<double> descuento { get; set; }
        public Nullable<double> credito { get; set; }
        public int indtll { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> subtotal1 { get; set; }
        public Nullable<double> itebis { get; set; }
        public Nullable<double> devuelta { get; set; }
        public string ncf { get; set; }
        public string rnc { get; set; }
        public string cliente { get; set; }
        public string tipodocumento { get; set; }
        public Nullable<double> totalItbis { get; set; }
        public Nullable<double> itbis { get; set; }
    }
}
